version: '2.2'
services:
  test-routes:
    image: alpine:latest
    environment:
      URLS: |
        http://asp-nginx/ 403
        http://asp-nginx/.htaccess 401
        http://asp-nginx/ASP/ 200
        http://asp-nginx/ASP/aspx 401
        http://asp-nginx/ASP/bf2statistics.php 403
        http://asp-nginx/ASP/frontend/css/bootstrap.min.css 200
        http://asp-nginx/ASP/frontend/images/maps/foo.png 200
        http://asp-nginx/ASP/frontend/images/ranks/foo.png 200
        http://asp-nginx/ASP/frontend/images/armies/foo.png 200
        http://asp-nginx/ASP/frontend/css/bootstrap.min.css 200
        http://asp-nginx/ASP/frontend 401
        http://asp-nginx/ASP/getleaderboard.aspx 200
        http://asp-nginx/ASP/getplayerinfo.aspx 200
        http://asp-nginx/ASP/system 401
    networks:
      - bf2-network
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu
          echo "$$URLS" | awk NF | while read -r i j; do
              if wget -q -SO- "$$i" 2>&1 | grep "HTTP/1.1 $$j " > /dev/null; then
                  echo "PASS: $$i"
              else
                  echo "FAIL: $$i"
                  exit 1
              fi
          done

networks:
  bf2-network:
    name: bf2-network
