version: '2.2'
services:
  init-container:
    image: alpine:latest
    volumes:
      - backups-volume:/src/ASP/system/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - cache-volume:/src/ASP/system/cache
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
      - db-volume:/var/lib/mysql
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          echo "Granting php write permissions"
          chown -R 82:82 /src/ASP/system/backups
          find /src/ASP/system/backups -type d -exec chmod 750 {} \;
          find /src/ASP/system/backups -type f -exec chmod 640 {} \;

          chown -R 82:82 /src/ASP/system/cache
          find /src/ASP/system/cache -type d -exec chmod 750 {} \;
          find /src/ASP/system/cache -type f -exec chmod 640 {} \;

          chown -R 82:82 /src/ASP/system/logs
          find /src/ASP/system/logs -type d -exec chmod 750 {} \;
          find /src/ASP/system/logs -type f -exec chmod 640 {} \;

          mkdir -p /src/ASP/system/snapshots/failed
          mkdir -p /src/ASP/system/snapshots/processed
          mkdir -p /src/ASP/system/snapshots/unauthorized
          mkdir -p /src/ASP/system/snapshots/unprocessed
          chown -R 82:82 /src/ASP/system/snapshots
          find /src/ASP/system/snapshots -type d -exec chmod 750 {} \;
          find /src/ASP/system/snapshots -type f -exec chmod 640 {} \;

          echo "Granting db write permissions"
          chown -R 999:999 /var/lib/mysql

  nginx:
    image: leojonathanoh/asp:nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Customize as needed
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - init-container
      - php
    restart: unless-stopped

  php:
    image: leojonathanoh/asp:php
    volumes:
      - ./config/ASP/config.php:/src/ASP/system/config/config.php # Main config file. Must be writeable or else ASP will throw an exception. Customize as needed
      # - ./config/ASP/armyAbbreviationMap.php:/src/ASP/system/config/armyAbbreviationMap.php:ro  # Optional: Customize as needed if using a custom mod
      # - ./config/ASP/backendAwards.php:/src/ASP/system/config/backendAwards.php:ro              # Optional: Customize as needed if using a custom mod
      # - ./config/ASP/ranks.php:/src/ASP/system/config/ranks.php:ro                              # Optional: Customize as needed if using a custom mod
      - ./config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro # Customize as needed
      - backups-volume:/src/ASP/system/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - cache-volume:/src/ASP/system/cache
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
    networks:
      - default
    depends_on:
      - init-container
    restart: unless-stopped

  db:
    image: mariadb:10.8
    environment:
      - MARIADB_ROOT_PASSWORD=ascent
      # - MARIADB_USER=myuser # Uncomment this if you want to create a regular user
      # - MARIADB_PASSWORD=mypassword # Uncomment this if you want to create a regular user
      - MARIADB_DATABASE=bf2stats
    volumes:
      # Seed the database on the first run. No need to use the ASP dashboard's installer. Note that the .sql file are executed in alphabetical order of their names.
      - ./src/ASP/system/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./src/ASP/system/sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
      - db-volume:/var/lib/mysql
    networks:
      - default
    depends_on:
      - init-container
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2-fpm-alpine
    environment:
      # - PMA_ABSOLUTE_URI=https://phpmyadmin.example.com # Enable this if behind a reverse proxy
      - PMA_HOST=db
    ports:
      - 8080:80
    networks:
      - default
    restart: unless-stopped

networks:
  default:

volumes:
  backups-volume:
  cache-volume:
  logs-volume:
  snapshots-volume:
  db-volume:
